name: Sync Fork (mirror, no-marketplace)

on:
  schedule:
    - cron: '0 3 * * *'   # Todos los días 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # necesario para pushear
    steps:
      - name: Configurar Git
        run: |
          git version
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Inicializar repo y remotos
        run: |
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git remote add upstream https://github.com/DragonJAR/n8n-workflows.git
          git fetch origin
          # si tu rama principal es "master", cambia main -> master en las 2 líneas siguientes
          git checkout -B main origin/main || git checkout -B main

      - name: Igualar con upstream/main (mirror)
        run: |
          git fetch upstream
          git reset --hard upstream/main
          git push origin main --force
