name: Sync Fork (mirror)

on:
  schedule:
    - cron: '0 3 * * *'   # Todos los días a las 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/DragonJAR/n8n-workflows.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Reset fork to match upstream/main
        run: |
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
